apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-devsecops
  region: us-east-1
  version: "1.31"

availabilityZones:
  - us-east-1a
  - us-east-1b

iam:
  withOIDC: false
  serviceRoleARN: arn:aws:iam::397608651921:role/c208559a5301072l14970659t1w397608-LabEksClusterRole-UQzLtTS8M4N6

managedNodeGroups:
  - name: ng-devsecops
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: vockey
    labels:
      role: worker
    iam:
      instanceRoleARN: arn:aws:iam::397608651921:role/c208559a5301072l14970659t1w397608651-LabEksNodeRole-JOzkVjgrCyxo
